#!/bin/sh
#!/usr/bin/env ruby
#
# hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# 
export LC_ALL=en_US.UTF-8
set -eu
script_path=$(git rev-parse --show-toplevel)/githooks
ruby $script_path/PreCommitLint.rb -w $script_path
exit 0